### ISSUE TITLE
odr-violation (0x0000004fedc0)

### ISSUE THREAD

**Issue by yangfar** [GregorBudweiser/pngenc#1]
When I use the ./pngenc_test img_uncompressed.png, one crash occurs.
The following is the details.

=================================================================
==14549==ERROR: AddressSanitizer: odr-violation (0x0000004fedc0):
  [1] size=4 'BASE' /home/hjsz/fuzz_software/pngenc-master/source/pngenc/adler32.c:141:11
  [2] size=4 'BASE' /home/hjsz/fuzz_software/pngenc-master/source/pngenc/adler32.c:141:11
These globals were registered at these points:
  [1]:
    #0 0x42e7ad in __asan_register_globals (/home/hjsz/fuzz_software/pngenc-master/build/bin/pngenc_test+0x42e7ad)
    #1 0x4d3c59 in asan.module_ctor (/home/hjsz/fuzz_software/pngenc-master/build/bin/pngenc_test+0x4d3c59)

  [2]:
    #0 0x42e7ad in __asan_register_globals (/home/hjsz/fuzz_software/pngenc-master/build/bin/pngenc_test+0x42e7ad)
    #1 0x7fe9948b68db in asan.module_ctor (/home/hjsz/fuzz_software/pngenc-master/build/lib/libpngenc.so+0x68db)

==14549==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'BASE' at /home/hjsz/fuzz_software/pngenc-master/source/pngenc/adler32.c:141:11
==14549==ABORTING

### Version
Latest commit
### Environment
Ubuntu 20

Report of the Information Security Laboratory of Ocean University of China @OUC_ISLOUC @OUC_Blue_Whale

**Comment by GregorBudweiser** [comment]
Thanks for reporting. Should be fixed on master (as of commit beeabf66e55ba003079fb2184792856c7a72ea28 ).
